output "site_bucket_name" {
  value = aws_s3_bucket.site.bucket
}

output "member_files_bucket_name" {
  value = aws_s3_bucket.member_files.bucket
}

output "cloudfront_distribution_id" {
  value = aws_cloudfront_distribution.site.id
}

output "cloudfront_domain_name" {
  value = aws_cloudfront_distribution.site.domain_name
}

output "site_url" {
  value = "https://${var.site_domain}"
}

output "site_app_version" {
  description = "Deploy/build version generated by Terraform and exposed to the site via config.js."
  value       = local.site_app_version
}

output "route53_zone_id" {
  value = data.aws_route53_zone.site.zone_id
}

output "acm_certificate_arn" {
  value = aws_acm_certificate.site.arn
}

output "cognito_user_pool_id" {
  value = aws_cognito_user_pool.members.id
}

output "cognito_client_id" {
  value = aws_cognito_user_pool_client.site.id
}

output "cognito_hosted_ui_domain" {
  value = "https://${aws_cognito_user_pool_domain.site.domain}.auth.${var.aws_region}.amazoncognito.com"
}

output "member_api_base_url" {
  value = aws_apigatewayv2_stage.default.invoke_url
}

output "member_metadata_table_name" {
  value = aws_dynamodb_table.member_metadata.name
}

output "ses_email_domain" {
  value = aws_ses_domain_identity.club_mail.domain
}

output "ses_from_email" {
  value = local.ses_from_email
}

output "ses_configuration_set_name" {
  value = aws_ses_configuration_set.club_mail.name
}

output "ses_mail_from_domain" {
  value = aws_ses_domain_mail_from.club_mail.mail_from_domain
}

output "mail_state_table_name" {
  value = aws_dynamodb_table.mail_state.name
}

output "event_reminder_schedule_name" {
  value = aws_scheduler_schedule.event_reminders_daily.name
}

output "vehicle_registration_reminder_schedule_name" {
  value = aws_scheduler_schedule.vehicle_registration_reminders_daily.name
}

output "chat_table_name" {
  value = aws_dynamodb_table.chat.name
}
output "member_api_id" {
  value = aws_apigatewayv2_api.member_api.id
}

output "member_api_invoke_url" {
  value = aws_apigatewayv2_stage.default.invoke_url
}

output "cognito_domain_prefix" {
  value = aws_cognito_user_pool_domain.site.domain
}

output "member_files_lambda_name" {
  value = aws_lambda_function.member_files.function_name
}

output "chat_notification_worker_lambda_name" {
  value = aws_lambda_function.chat_notification_worker.function_name
}

output "chat_notifications_queue_url" {
  value = aws_sqs_queue.chat_notifications.id
}

output "chat_notifications_dlq_url" {
  value = aws_sqs_queue.chat_notifications_dlq.id
}
